[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = { version = "2.8.1" }
pest_derive = { version = "2.8.1", features = ["grammar-extras"] }
clap = { version = "4.5.45", features = ["derive"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
inkwell = { version = "0.6.0", features = ["llvm14-0"] }
tklog = "0.3.0"
log = "0.4.29"

[profile.dev]
opt-level = 0
debug = 2   # 或 "full"
incremental = false

