// ===== SysY grammar for pest =====
// 顶层入口
File        = { SOI ~ (WS | KEYWORD | Operator | Ident | IntConst | ErrorStmt)+ ~ EOI }
                     // 需在语义阶段保证常量可求值
// ---------- 词法 ----------
Ident       = { !KEYWORD ~ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

// 整型常量：十进制 / 八进制 / 十六进制
IntConst    = _{ HexConst | OctConst | DecConst }
HexConst    = @{ ("0x" | "0X") ~ ASCII_HEX_DIGIT+ }
OctConst    = @{ "0" ~ ASCII_OCT_DIGIT* }       // "0" 也是八进制零
DecConst    = @{ '1'..'9' ~ ASCII_DIGIT* }

LINE_COMMENT= _{ "//" ~ (!NEWLINE ~ ANY)* }     // 不吃换行，由 WHITESPACE 吃
BLOCK_COMMENT=_{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
WS  = _{ " " | "\t" | NEWLINE | LINE_COMMENT | BLOCK_COMMENT }

// ---------- 关键字（保留字） ----------
Const    = { "const" }
Int      = { "int" }
Void     = { "void" }
If       = { "if" }
Else     = { "else" }
While    = { "while" }
Break    = { "break" }
Continue = { "continue" }
Return   = { "return" }
KEYWORD     = _{ Const | Int | Void | If | Else | While | Break | Continue | Return }

// ---------- 错误同步（用于一次输出所有语法错误） ----------
// 顶层：跳过到下一个 ';' 或 '}'（若无则尽量吃到行尾/文件尾）
// 块内：同上；留在 Block 中继续解析
ErrorStmt   = {
    (!(Semicolon | CloseBrace ) ~ ANY)+ ~ (Semicolon | CloseBrace)?
}

Plus = { "+" }

Minus = { "-" }

Mul = { "*" }

Div = { "/" }

Mod = { "%" }

Assign = { "=" }

Semicolon = { ";" }

Equal = { "==" }

NotEqual = { "!=" }

Less = { "<" }

Greater = { ">" }

LessEqual = { "<=" }

GreaterEqual = { ">=" }

Not = { "!" }

And = { "&&" }

Or = { "||" }

OpenParen = {
    "("
}
CloseParen = {
    ")"
}

OpenBrace = {
    "{"
}
CloseBrace = {
    "}"
}

OpenBracket = { "[" }
CloseBracket = { "]" }

Comma = { "," }

Operator = _{
    Equal |        // ==
    NotEqual |     // !=
    LessEqual |    // <=
    GreaterEqual | // >=
    And |          // &&
    Or |           // ||
    Assign |       // =
    Less |         // <
    Greater |      // >
    Plus |         // +
    Minus |        // -
    Mul |          // *
    Div |          // /
    Mod |          // %
    Not |          // !
    Semicolon |    // ;
    Comma |        // ,
    OpenBracket |  // [
    CloseBracket | // ]
    OpenParen |    // (
    CloseParen |   // )
    OpenBrace |    // {
    CloseBrace     // }
}
